// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jgidrekaaqztxdiidbnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnaWRyZWthYXF6dHhkaWlkYm5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzNzA4MDMsImV4cCI6MjA3NTk0NjgwM30.H-2y_2gYCwKslU5G3yzbaZE8-R9WX5sLgLKCc7fKMvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);